import 'package:flutter/material.dart';
import 'package:graduation_project/features/auth/presentation/screens/change_password_screen.dart';
import 'package:graduation_project/features/auth/presentation/screens/choose_user_screen.dart';
import 'package:graduation_project/features/auth/presentation/screens/forget_password_screen.dart';
import 'package:graduation_project/features/auth/presentation/screens/login_screen.dart';
import 'package:graduation_project/features/auth/presentation/screens/reset_password.dart';
import 'package:graduation_project/features/auth/presentation/screens/verfiy_code_screen.dart';
import 'package:graduation_project/features/auth/presentation/screens/register_screen.dart';
import 'package:graduation_project/features/doctors/presentation/screens/create_apointment_screen.dart';
import 'package:graduation_project/features/doctors/presentation/screens/doctor_appointments_screen.dart';
import 'package:graduation_project/features/doctors/presentation/screens/work_hours_screen.dart';
import 'package:graduation_project/features/profile/presentation/screen/update_profile.dart';
import 'package:graduation_project/features/splash_screen.dart';
import 'package:graduation_project/features/user/booking/presentation/screen/booking_screen.dart';
import 'package:graduation_project/features/user/clinic/presentation/screen/clinic_screen.dart';
import 'package:graduation_project/features/user/clinic/presentation/widget/clinic_details.dart';
import 'package:graduation_project/features/doctor/presentation/screen/doctor_screen.dart';
import 'package:graduation_project/features/doctor/presentation/widgets/doctor_details.dart';
import 'package:graduation_project/features/home/presentation/screens/doctor_home_screen.dart';
import 'package:graduation_project/features/home/presentation/screens/patient_home_screen.dart';
import 'package:graduation_project/features/user/onBoarding/presentation/screen/on_boarding_screen.dart';
import 'package:graduation_project/features/profile/presentation/screen/profile_screen.dart';

class Routes {
  static const patientHome = PatientHomeScreen.patientHome;
  static const doctorHome = DoctorHomeScreen.doctorHome;
  static const onBoarding = OnBoardingScreen.onBoarding;
  static const register = RegisterScreen.register;
  static const chooseUser = ChooseUserScreen.chooseUser;
  static const login = LoginScreen.login;
  static const splash = SplashScreen.splashScreen;
  static const clinic = ClinicScreen.clinic;
  static const doctor = DoctorsScreen.doctor;
  static const profile = ProfileScreen.profile;
  static const booking = BookingTab.booking;
  static const forgetPassword = ForgetPasswordScreen.forgetPassword;
  static const clinicDetails = ClinicDetails.clinicDetails;
  static const doctorsDetails = DoctorDetails.dectorDetails;
  static const verifycode = VerifyCodeScreen.verifyCodeScreen;
  static const resetPassword = ResetPassword.resetPassword;
  static const changePassword = ChangePasswordScreen.changePassword;
  static const updateprofile = UpdateProfileScreen.update;
  static const doctorAppointments = DoctorAppointmentsScreen.doctorAppointments;
  static const worksHours = WorksHoursScreen.worksHours;
  static const createAppointment = CreateAppointmentScreen.createAppointment;
}
